### ISSUE TITLE
Improvement Suggestion: Bigger Dots

### ISSUE THREAD

**Issue by SeaCrow** [dingram/glypher#10]
Compared to orginal Ingress glyphhack, Glypher's glyphs are harder to draw (more often dot don't light up)
![1](https://cloud.githubusercontent.com/assets/7692994/3076457/a9ca7716-e3df-11e3-9034-78d65231f8a2.png)  ![2](https://cloud.githubusercontent.com/assets/7692994/3076458/a9cb7e04-e3df-11e3-8c85-f6c432aa5563.png)
Both created with same finger movement. My suggestion is to make dots slightly bigger.

**Comment by kentfredric** [comment]
+1 Im not entirely sure if this is the option I'm looking for, but something about the UI presently strikes me as much more awkward to use than the official ingress glyph UI. Its really hard to draw the lines even if you know what you're doing, whereas ingress as long as you know where you're headed it works.

Maybe bigger targets would help here. 

But either way, getting a negative result for a postive action impedes reinforcement of the learning, and using Glypher just leaves me frustrated.

**Comment by dingram** [comment]
Apologies. With the release of 1.10, I have made two changes: the hit targets are larger by default, and you can now configure their relative size. I hope that helps!
