### ISSUE TITLE
iOS port

### ISSUE THREAD

**Issue by deucalion** [dingram/glypher#12]
Hi!

Would you mind creating a port to iOS for the newcomers on iPhones etc?
(I would - of course - be willing to pay for an app like that in the AppStore.)

Thank you for your consideration!

**Comment by TimAEllis** [comment]
Hi, any update on the possibility of an iOS Port?
I would be willing to help code (or even just code the iOS version).

:)

**Comment by dingram** [comment]
Apologies; other things in life had been taking up my time.

I would like to be able to develop an iOS version, but unfortunately I would have to purchase an Apple computer (and likely an iOS device) to do so and I don't have the funds for that. I believe there are alternatives available, though I don't have any details.
