### ISSUE TITLE
Imperfect glyph is not recognized

### ISSUE THREAD

**Issue by mbrunetto** [dingram/glypher#14]
One way to draw it:
![image](https://cloud.githubusercontent.com/assets/9956573/5195480/68e3f036-74eb-11e4-839f-c3ada4bd3e8e.png)

Another way to draw it:
![image](https://cloud.githubusercontent.com/assets/9956573/5195492/8879c808-74eb-11e4-8d80-2cf8dfa23d58.png)

The trick is, drawing it in a line such that the lower left and upper right are connected twice, once touching the point in the middle, and a second time when they aren't.
I have a video of another way to draw it if you would like.

**Comment by dingram** [comment]
This has been fixed in v1.10.
