### ISSUE TITLE
Missing glyphs

### ISSUE THREAD

**Issue by fenhl** [dingram/glypher#16]
The app does not recognize the following glyphs:
-   0–6–3–9–0 (Victory)
-   0–6–10–0–9–10–3 (N'zeer)
-   0–10–8–4–5–9–10–3 (Interrupt)
-   0–10–9–8–4 (Chase)
-   1–6–10–8–9–4 (Reincarnate)
-   1–7–10–8–5 (Worth)
-   2–3–4–5–0–1–7–8–9–6–10 (Unbounded)
-   2–7–6–1–0–5–9–8–4 (Legacy)
-   2–7–10–6–0–9–10–8–4 (Perspective)
-   5–9–0–6–9–8 (Mystery)
-   7–3–8–7–6–10–9–8 (Presence)

**Comment by dingram** [comment]
Thanks! I had not seen these so far. I'll add them to 1.12. My most recent source was http://www.ingress.tv/glyphs.html, which doesn't contain those yet.

Could you show me how you number your calibration grid please? I started from 1 as the top dot, then increase left-to-right, top-to-bottom. This leads to:

```
    1
2       3
  4   5
    6
  7   8
9       10
   11
```

**Comment by dingram** [comment]
I've found a source and added the new glyphs ready for v1.12.

**Comment by fenhl** [comment]
My calibration grid is taken from [ingress-glyph-tools](https://github.com/gm9/ingress-glyph-tools/blob/master/glyph-tools.js#L226-L237); I have found that this is used in several projects.

```
      0
5            1
   9      6
      10
   8      7
4            2
      3
```
