### ISSUE TITLE
Current glyph not re-showing name after incorrect entry

### ISSUE THREAD

**Issue by Eggmansworld** [dingram/glypher#3]
v1.07-beta-2 
1. Glyph name pops up on screen.
2. I incorrectly draw another valid glyph, or just get it wrong.
3. It shows me the name of the glyph I just drew (if I drew something else right), or "unknown glyph".
   4, Does not clear the incorrectly drawn glyph name and re-show me the name of the glyph I'm supposed to draw.  It just expects me to remember.

My memory is horrible, so I actually end up forgetting what I was supposed to draw in the first place.﻿

**Comment by fenhl** [comment]
Why is this closed? It's still an issue.

**Comment by dingram** [comment]
Good question. Because I didn't make a comment at the time, I assume I thought I'd fixed it. Reopening.

**Comment by dingram** [comment]
Fixed in v1.12
