### ISSUE TITLE
Some settings only applicable on restart

### ISSUE THREAD

**Issue by Schrubbi** [dingram/glypher#6]
When changing "show glyph before drawing", "First reminder is a hint" or "New glyph on failure" the changes aren't applied until the app is restarted (in Single random glyph mode)
At least changing it or skipping to the next glyph didn't do the trick and there seems to be no other option to get it applied.

**Comment by malles** [comment]
Same experience here.

**Comment by dingram** [comment]
Thanks, I'll look into fixing this for 1.12.

**Comment by dingram** [comment]
This was actually fixed as a consequence of changes in v1.10
